
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";  
import "./globals.css";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (

  <html lang="en">
    <body className={`${inter.className} antialiased`}>
      <TRPCReactProvider>
        <NuqsAdapter>
          <Toaster />
          {children}
        </NuqsAdapter>
      </TRPCReactProvider>
    </body>
  </html>
);
}